fix: include direct emitter results in ltp export
equinor/ecalc pull request #305
Opened 2023-11-29 13:45 UTC by frodehk

## Why is this pull request needed?

Venting and fugitive emissions are currently modelled as `FUELCONSUMERS` (in most models), but it should be possible to get the same results if setting up these emission types as `VENTING_EMITTERS` (which is more correct). 

- Venting emitter results are not reported to ltp export
- Loading/storage volumes are not reported to ltp export, but is required in Centuries. Currently not possible in eCalc, requires changes to the VENTING_EMITTERS, and more input from user in yaml

## What does this pull request change?

- [ ] EmissionQuery is updated to include venting emitters. Up til now it has only included fuel consumers.

## Issues related to this change:
https://equinor-ecalc.atlassian.net/browse/ECALC-409?atlOrigin=eyJpIjoiZDkzMTFmNzg1ZTQ0NDI0M2EwYzhiY2RlZTNlN2E5YzgiLCJwIjoiaiJ9

2023-11-30 09:16 UTC, TeeeJay requested changes
Nice catch, but I think we need some additional things:

* add an emitter equivalent to what previously has been a fuel consumer with no fuel, to verify that the result is the same
* add the emitter as a temporal model, to verify correctness with temporal models
* verify that the snapshot does not change?

2023-11-30 09:35 UTC, frodehk commented on src/libecalc/presentation/exporter/queries.py
> +            if self.fuel_type_category is None:
Remember that `self` is the `EmissionQuery` itself. It is not related to if the venting emitter has fuel (which it shouldn´t). The query can be asking for CO2 from diesel e.g., where the only filters are installation category (fixed), fuel type category (diesel) and emission type (CO2). But we could of course check if the venting emitter is tagged with a fuel category and return an error. The main point here is that venting emissions should only be included/accounted for when fuel type is not asked for.

2023-11-30 09:37 UTC, TeeeJay commented
comment from the initial change from `direct_emitter` to `venting_emitter`:

> this is a "huge" breaking change, and should have been marked in the git commit message with `refactor!:` and `BREAKING CHANGE` in the footer. Changelog and migration guide must also be updated.

please include that as a part of this commit/PR then :)

2023-11-30 09:40 UTC, frodehk commented
> comment from the initial change from `direct_emitter` to `venting_emitter`:
> 
> > this is a "huge" breaking change, and should have been marked in the git commit message with `refactor!:` and `BREAKING CHANGE` in the footer. Changelog and migration guide must also be updated.
> 
> please include that as a part of this commit/PR then :)

You mean the breaking change, or only changelog/migration guide?

2023-11-30 09:52 UTC, TeeeJay commented
> > comment from the initial change from `direct_emitter` to `venting_emitter`:
> > > this is a "huge" breaking change, and should have been marked in the git commit message with `refactor!:` and `BREAKING CHANGE` in the footer. Changelog and migration guide must also be updated.
> > 
> > 
> > please include that as a part of this commit/PR then :)
> 
> You mean the breaking change, or only changelog/migration guide?

both :) ...

2023-11-30 10:05 UTC, TeeeJay commented on docs/docs/changelog/v8-6.md
> +- Change name from DIRECT_EMITTER to VENTING_EMITTER in input Yaml-file.
you must create a new changelog file for v8-7 :)

2023-11-30 10:36 UTC, frodehk commented
> Nice catch, but I think we need some additional things:
> 
> * add an emitter equivalent to what previously has been a fuel consumer with no fuel, to verify that the result is the same
> * add the emitter as a temporal model, to verify correctness with temporal models
> * verify that the snapshot does not change?

I am not sure what we achieve with doing this. When modelling venting emitters as fuel consumers, it has to be energy usage to have emissions (i.e. a fuel rate). This is not correct, as venting emitters are emissions to air (not combustion). Hence, there will be a difference if we try to mimic the venting emissions as a fuel consumer using the DIRECT energy usage model. If we use no fuel the energy usage will be the same in the two approaches, but the fuel consumer will have no emissions. If we adjust the fuel and emission factors (for the fuel consumer approach), the emissions will be the same but the energy usage will be different (too high for the fuel consumer approach).

2023-12-07 18:48 UTC, frodehk commented on src/libecalc/presentation/exporter/queries.py
> +                                unit_in = emission_volumes.unit
emission.rate.unit is set before the query (e.g. `t/d`), in the to_volumes() it is converted to `t`. So the assumption is made earlier. The docs states that the emission rate should be in kg/day, and the assumption is done in FuelModel.evaluate_emissions(), where `kg/d` is converted to `t/d` - hence, assuming input is `kg/d`.

2023-12-08 12:12 UTC, jsolaas commented on src/libecalc/presentation/exporter/queries.py
> +                                unit_in = emission_volumes.unit
Makes sense to me, for this to fail the unit for fuel_consumers (emissions) and direct emitter would have to be different, and that is something we control.

It won't be an issue when adding units to venting_emitter either as we will convert into kg (probably). Is that something you are planning to do?

2023-12-08 12:14 UTC, jsolaas approved these changes

2023-12-08 12:14 UTC, jsolaas commented on docs/docs/about/migration_guides/v8-6_to_v8-7.md
> +sidebar_position: 4
Wrong title and description

2023-12-08 12:16 UTC, frodehk commented on src/libecalc/presentation/exporter/queries.py
> +                                unit_in = emission_volumes.unit
I am adding unit to venting_emitter in another ongoing pr (will convert to kg as well).

2023-12-11 15:24 UTC, TeeeJay approved these changes

2023-12-11 19:31 UTC, frodehk commented
> Nice catch, but I think we need some additional things:
> 
> * add an emitter equivalent to what previously has been a fuel consumer with no fuel, to verify that the result is the same
> * add the emitter as a temporal model, to verify correctness with temporal models
> * verify that the snapshot does not change?

I agree in the need of a test for venting emitters. I will add one as soon as the new pr with yaml classes is merged.

2023-12-11 19:32 UTC, merged