chore: do not allow control margin for simplified variable speed train
equinor/ecalc pull request #569
Opened 2024-08-16 12:04 UTC by frodehk

BREAKING CHANGE: `CONTROL_MARGIN` not allowed for `SIMPLIFIED_VARIABLE_SPEED_COMPRESSOR_TRAIN`

ECALC-1483

## Have you remembered and considered?

- [ ] I have remembered to update documentation
- [ ] I have remembered to update manual changelog (`docs/docs/changelog/next.md`)
- [ ] I have remembered to update migration guide (`docs/docs/migration_guides/`)
- [ ] I have committed with `BREAKING:` in footer or `!` in header, if breaking
- [ ] I have added tests (if not, comment why)
- [ ] I have used conventional commits syntax (if you squash, make sure that conventional commit is used)
- [ ] I have included the Jira issue ID somewhere in the commit body (`ECALC-XXXX`)

## Why is this pull request needed?

Adding a `CONTROL_MARGIN` to `SIMPLIFIED_VARIABLE_SPEED_COMPRESSOR_TRAIN` has no effect. eCalc ignores it, but user is not notified. 

## What does this pull request change?

New behavior: eCalc will fail if `CONTROL_MARGIN` is specified (only pydantic yaml-validation for web, not cli)

## Issues related to this change:
https://equinor-ecalc.atlassian.net/browse/ECALC-1483?atlOrigin=eyJpIjoiN2M0OWMzMTFiN2FlNDFkMDg1MmViNTdiODM2NTdjMDYiLCJwIjoiaiJ9

2024-08-16 14:34 UTC, TeeeJay commented on src/libecalc/presentation/yaml/yaml_types/models/yaml_compressor_trains.py
> +                        f"{EcalcYamlKeywords.models_type_compressor_train_single_speed}, "
can the list of compatible model types be retrived dynamically isntead of "hardcoding" here, in case it changes?

2024-08-16 14:35 UTC, TeeeJay commented on src/libecalc/presentation/yaml/yaml_types/models/yaml_compressor_trains.py
> +
please add a test - or update a test to verify correctness? if possible.

2024-08-16 14:36 UTC, TeeeJay requested changes
nice descriptive error - but we should have a test to verify when it is applicable - if possible

2024-08-20 07:10 UTC, olelod commented
Should we include the same behaviour for PRESSURE_DROP_AHEAD_OF_STAGE? Defining it for a simplified train does not have any effect.

2024-08-20 10:29 UTC, TeeeJay commented
> Should we include the same behaviour for PRESSURE_DROP_AHEAD_OF_STAGE? Defining it for a simplified train does not have any effect.

Should have the same check/test for that yes. Create an issue to have it prioritized :)

2024-08-21 09:05 UTC, TeeeJay approved these changes

2024-08-21 09:19 UTC, merged